### ISSUE TITLE
davs2 version issue

### ISSUE THREAD

**Issue by yaowangvrviu** [pkuvcl/buildFFmpegAVS2#4]
using the **lasted** version of davs2.
./configure --enable-static --disable-shared --enable-gpl ...  --enable-libdavs2
**ERROR: davs2 >= 1.5.115 not found using pkg-config**

open the davs2.pc file 
Name: davs2
Description: AVS2 (IEEE 1857.4) decoder library
Version: **1.5.0**   <=================

in configure file
enabled libdavs2          && require_pkg_config libdavs2 "davs2 >= **1.5.115**" davs2.h davs2_decoder_open

What's the lasted davs2 version?

**Comment by luofalei** [comment]
It seems that you are not operating in a repository, thus the version number is `1.5.0`.
The last number is generated when it is in a git repository.
This could be fixed by:
(1) using git clone to fetch these sources;
or (2) fix the version number check of `libdavs2` in the `FFmpeg` configuration script.

**Comment by yaowangvrviu** [comment]
Using the method (2) I fix this issue.
Thank you luofalei,
